import sys
from datetime import datetime
from pathlib import Path

if len(sys.argv) != 4:
    print("Usage:")
    print('python3 report.py "Business Name" "Website URL" "City, State"')
    sys.exit()

business = sys.argv[1]
website = sys.argv[2]
location = sys.argv[3]

reports_dir = Path("reports")
reports_dir.mkdir(exist_ok=True)

safe_name = business.replace(" ", "")

date_stamp = datetime.now().strftime("%Y%m%d")

file_path = reports_dir / f"{safe_name}_Report_{date_stamp}.txt"

report = f"""
ROGERS HOLDINGS LLC
LOCAL BUSINESS REPORT

Business: {business}
Website: {website}
Location: {location}

WEBSITE AUDIT
-------------
Mobile Friendly: Review Required
Call To Action: Review Required
Contact Information: Review Required
Services Listed: Review Required

GOOGLE BUSINESS PROFILE
-----------------------
Reviews: Review Required
Photos: Review Required
Categories: Review Required

RECOMMENDED FIXES
-----------------
1. Complete website review
2. Complete Google Business Profile review
3. Improve local SEO

Generated by Rogers Holdings LLC
"""

with open(file_path, "w") as f:
    f.write(report)

print(f"Report created: {file_path}")